### ISSUE TITLE
Throws a errror at Node environment ("ReferenceError: define is not defined")

### ISSUE THREAD

**Issue by AlexanderSychev** [psfe/micro-event#1]
I tried to use your library as simple univeral analog of Node Events module. When I tried to run tests by Mocha, I received a error: `ReferenceError: define is not defined`. When a tried just "run" your module directly, this error was throwed too:
```
/home/alexander/Projects/electron-rpc/node_modules/micro-event/index.js:1
(function (exports, require, module, __filename, __dirname) { define(function () {
                                                              ^

ReferenceError: define is not defined
    at Object.<anonymous> (/home/alexander/Projects/electron-rpc/node_modules/micro-event/index.js:1:63)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/alexander/Projects/electron-rpc/packages/electron-rpc-async-queue/dist/Task.js:4:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/alexander/Projects/electron-rpc/packages/electron-rpc-async-queue/dist/AsyncQueue.js:4:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/alexander/Projects/electron-rpc/packages/electron-rpc-async-queue/dist/AsyncQueue.unit.js:6:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/alexander/Projects/electron-rpc/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/alexander/Projects/electron-rpc/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/alexander/Projects/electron-rpc/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/home/alexander/Projects/electron-rpc/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```
Looks like incorrectly builded UMD module.

**Comment by AlexanderSychev** [comment]
Bundles at `/dist` subdirectory throws that error too.

**Comment by oott123** [comment]
Sorry for the inconvenience. Would you mind to use micro-event@1.1.1 instead at this time? Seems 2.0.0 breaks node.js support.

**Comment by harttle** [comment]
Seems 2.0.0 is not in the git history thus un-trackable, just republished @1.1.1 to @3.0.0  If there're still problems, let us know.
